name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.8.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      # Debug ESLint config files
      - name: Debug ESLint Configuration
        run: |
          echo "Listing config files:"
          ls -la .eslint*
          echo "Forcibly removing any .js config file:"
          rm -f .eslintrc.js
          echo "Confirming .cjs exists:"
          ls -la .eslint*

      - name: Run Knip for unused code analysis
        run: pnpm knip
        continue-on-error: true # Optional during initial integration

      - name: Type Check
        run: pnpm type-check

      - name: Build
        run: pnpm build

      - name: Run main tests (excluding slow tests)
        run: >-
          pnpm exec vitest run --testNamePattern="^((?!Resilience: Subscription Memory Leaks).)*$"

  slow-tests:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.8.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Run slow memory leak tests
        run: >-
          pnpm exec vitest run --testNamePattern="Resilience: Subscription Memory Leaks"
