name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.8.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Ensure correct ESLint config
        run: |
          if [ -f ".eslintrc.js" ]; then
            mv .eslintrc.js .eslintrc.cjs
          fi

      - name: Lint
        continue-on-error: true # Temporarily allow linting to fail
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
