name: Deploy Docusaurus

on:
  push:
    branches: [main]
    paths:
      - "docs/**"

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: |
          cd docs
          pnpm install
      - name: Build website
        run: |
          cd docs
          pnpm build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
